-- Tabel untuk quiz_attempts
DROP TABLE IF EXISTS "quiz_attempts";
CREATE TABLE IF NOT EXISTS "quiz_attempts" (
  "id" TEXT,
  "mapel" TEXT,
  "answers" TEXT,
  "kelas" TEXT,
  "total" TEXT,
  "created_at" TEXT,
  "percent" TEXT,
  "user_id" TEXT,
  "score" TEXT,
  "jenjang" TEXT,
  "tipe" TEXT,
  "material_judul" TEXT,
  "material_id" TEXT,
  "bab" TEXT
);

INSERT INTO "quiz_attempts" ("id", "mapel", "answers", "kelas", "total", "created_at", "percent", "user_id", "score", "jenjang", "tipe", "material_judul", "material_id", "bab") VALUES ('5j6GK0H9AcjyQn1jhCVo', 'Matematika', '{"2k6YwCshG5jiw461VrQF":"C","WyWVH76FnyngBaNZiFkv":"A","KtTt2Zv3GC8qRQG5cPGp":"A","rBxqcUbz7sC1jpEgVpzP":"A","WVnVWd3rEd6Q6w9SpgIM":"C","sJbQLSl2k2lWYHPvcApt":"D","30AkaBcRoleVAGnB1mCN":"A","DfutJXC3DNlwmi6NMZ3x":"A","Dkl6xoeHXUrvPRXATsEX":"B","XYO5jsbFmTksEz2dxrc4":"A","UrOKUbjkwYg9zfKhn3cm":"A","KFJVLEMy3ocf63Xtqujg":"C","qjSk7WgHMR3B8aJzB7VI":"A","IHrNaOI9V5WsaNJmbfyy":"C","prmWyyinEzNVClbmhJbZ":"B","tLZ0Ls9hpaVITgBQFoSf":"A","3qu5thl6E6DBgMwRZ7En":"C","LCX9iXiNPdH39ExXKEDB":"D","ZeMl1NZQhZBpFbAnjSKP":"B","wzr4urdA0JRZWZcYMImo":"A","I3QdUAntAo0XKlL5F0gh":"A","CKhId6ml9hxJaxaH5ik4":"A","UXvBBjAmQgrTmzpqQu4s":"A","Ar3JQ0wfc7ywApHusg15":"A","GMmzEmcUehoCLX2y8z7G":"A"}', '11', '25', '{"_seconds":1787583684,"_nanoseconds":104334000}', '88', 'k8cyaD5lk0aKS44yhQb5', '22', 'SMA', 'Latihan Materi', NULL, NULL, NULL);
INSERT INTO "quiz_attempts" ("id", "mapel", "answers", "kelas", "total", "created_at", "percent", "user_id", "score", "jenjang", "tipe", "material_judul", "material_id", "bab") VALUES ('L5qu8MBvBAnbMynFpXZJ', 'Matematika', '{"hJZvKfpmf4M8GHbllr8T":"B","T6Cs2nJuCRG0vGgpOqtq":"B","CQGX0HoVKsVo7mAZwB5M":"B","qUiWTk7CmgY6h4qw00nY":"C","p7tYzKhLX9CXPKKqgo2n":"C","xGbMLUdtLrwheThAjeS9":"D","FCuEkbEMazdA9RUdCkyO":"A","NATjyn4rMycp9RphF1le":"C","XbL4uuox91BRiw8j18AT":"B","roedWprc6GbaAkVpwwLK":"A"}', '11', '10', '{"_seconds":1787841982,"_nanoseconds":528871000}', '90', 'gVA7Y1Bgh0mmaxWsMzGW', '9', 'SMA', 'Latihan Materi', 'Polinomial', '9maIAzJHiZFMzQIbq7DW', NULL);
INSERT INTO "quiz_attempts" ("id", "mapel", "answers", "kelas", "total", "created_at", "percent", "user_id", "score", "jenjang", "tipe", "material_judul", "material_id", "bab") VALUES ('Pm0T2TqGfXVFbpz9leOS', 'Matematika', '{"IHrNaOI9V5WsaNJmbfyy":"B","KFJVLEMy3ocf63Xtqujg":"C","GMmzEmcUehoCLX2y8z7G":"D","LCX9iXiNPdH39ExXKEDB":"D","UrOKUbjkwYg9zfKhn3cm":"A","XYO5jsbFmTksEz2dxrc4":"A","WVnVWd3rEd6Q6w9SpgIM":"C","Dkl6xoeHXUrvPRXATsEX":"B","I3QdUAntAo0XKlL5F0gh":"A","WyWVH76FnyngBaNZiFkv":"B","prmWyyinEzNVClbmhJbZ":"B","rBxqcUbz7sC1jpEgVpzP":"A","sJbQLSl2k2lWYHPvcApt":"D","KtTt2Zv3GC8qRQG5cPGp":"A","qjSk7WgHMR3B8aJzB7VI":"A","CKhId6ml9hxJaxaH5ik4":"A","UXvBBjAmQgrTmzpqQu4s":"A","DfutJXC3DNlwmi6NMZ3x":"A","ZeMl1NZQhZBpFbAnjSKP":"B","2k6YwCshG5jiw461VrQF":"C","3qu5thl6E6DBgMwRZ7En":"C","30AkaBcRoleVAGnB1mCN":"A","Ar3JQ0wfc7ywApHusg15":"A","wzr4urdA0JRZWZcYMImo":"B","tLZ0Ls9hpaVITgBQFoSf":"A"}', '11', '25', '{"_seconds":1787581943,"_nanoseconds":62663000}', '96', 'gVA7Y1Bgh0mmaxWsMzGW', '24', 'SMA', 'Latihan Materi', NULL, NULL, NULL);
INSERT INTO "quiz_attempts" ("id", "mapel", "answers", "kelas", "total", "created_at", "percent", "user_id", "score", "jenjang", "tipe", "material_judul", "material_id", "bab") VALUES ('QbWXSCyoMaYutzHM1nSL', 'Matematika', '{"2k6YwCshG5jiw461VrQF":"C","WyWVH76FnyngBaNZiFkv":"A","KtTt2Zv3GC8qRQG5cPGp":"A","rBxqcUbz7sC1jpEgVpzP":"A","WVnVWd3rEd6Q6w9SpgIM":"C","sJbQLSl2k2lWYHPvcApt":"D","30AkaBcRoleVAGnB1mCN":"A","DfutJXC3DNlwmi6NMZ3x":"A","Dkl6xoeHXUrvPRXATsEX":"B","XYO5jsbFmTksEz2dxrc4":"A","UrOKUbjkwYg9zfKhn3cm":"A","KFJVLEMy3ocf63Xtqujg":"C","qjSk7WgHMR3B8aJzB7VI":"A","IHrNaOI9V5WsaNJmbfyy":"C","prmWyyinEzNVClbmhJbZ":"B","tLZ0Ls9hpaVITgBQFoSf":"A","3qu5thl6E6DBgMwRZ7En":"C","LCX9iXiNPdH39ExXKEDB":"D","ZeMl1NZQhZBpFbAnjSKP":"B","wzr4urdA0JRZWZcYMImo":"A","I3QdUAntAo0XKlL5F0gh":"A","CKhId6ml9hxJaxaH5ik4":"A","UXvBBjAmQgrTmzpqQu4s":"A","Ar3JQ0wfc7ywApHusg15":"A","GMmzEmcUehoCLX2y8z7G":"A"}', '11', '25', '{"_seconds":1787583685,"_nanoseconds":907200000}', '88', 'k8cyaD5lk0aKS44yhQb5', '22', 'SMA', 'Latihan Materi', NULL, NULL, NULL);
INSERT INTO "quiz_attempts" ("id", "mapel", "answers", "kelas", "total", "created_at", "percent", "user_id", "score", "jenjang", "tipe", "material_judul", "material_id", "bab") VALUES ('fzc6n9dZyDjthwqJoqp1', 'Matematika Tingkat Lanjut', '{"T6Cs2nJuCRG0vGgpOqtq":"A","XbL4uuox91BRiw8j18AT":"A","p7tYzKhLX9CXPKKqgo2n":"A","CQGX0HoVKsVo7mAZwB5M":"A","FCuEkbEMazdA9RUdCkyO":"C","hJZvKfpmf4M8GHbllr8T":"B","xGbMLUdtLrwheThAjeS9":"C","qUiWTk7CmgY6h4qw00nY":"C","NATjyn4rMycp9RphF1le":"D","roedWprc6GbaAkVpwwLK":"C"}', '11', '10', '{"_seconds":1788096765,"_nanoseconds":292893000}', '20', 'S2IGhxBCfeQ40qgtQPro', '2', 'SMA', 'Latihan Materi', 'Fast-Track Materi', '9maIAzJHiZFMzQIbq7DW', NULL);
INSERT INTO "quiz_attempts" ("id", "mapel", "answers", "kelas", "total", "created_at", "percent", "user_id", "score", "jenjang", "tipe", "material_judul", "material_id", "bab") VALUES ('vCCoGtsagjXVyxrjkc5x', 'Matematika', '{"3qu5thl6E6DBgMwRZ7En":"C","CKhId6ml9hxJaxaH5ik4":"A","WyWVH76FnyngBaNZiFkv":"B","DfutJXC3DNlwmi6NMZ3x":"A","30AkaBcRoleVAGnB1mCN":"A","UrOKUbjkwYg9zfKhn3cm":"A","ZeMl1NZQhZBpFbAnjSKP":"D","wzr4urdA0JRZWZcYMImo":"B","I3QdUAntAo0XKlL5F0gh":"A","IHrNaOI9V5WsaNJmbfyy":"B","LCX9iXiNPdH39ExXKEDB":"D","qjSk7WgHMR3B8aJzB7VI":"A","sJbQLSl2k2lWYHPvcApt":"B","UXvBBjAmQgrTmzpqQu4s":"A","Ar3JQ0wfc7ywApHusg15":"A","2k6YwCshG5jiw461VrQF":"C","WVnVWd3rEd6Q6w9SpgIM":"C","Dkl6xoeHXUrvPRXATsEX":"B","KFJVLEMy3ocf63Xtqujg":"C","prmWyyinEzNVClbmhJbZ":"B","tLZ0Ls9hpaVITgBQFoSf":"A","XYO5jsbFmTksEz2dxrc4":"B","rBxqcUbz7sC1jpEgVpzP":"A","KtTt2Zv3GC8qRQG5cPGp":"A","GMmzEmcUehoCLX2y8z7G":"A"}', '11', '25', '{"_seconds":1787584451,"_nanoseconds":41615000}', '88', 'HVFTv67SyRgmpipE4GKW', '22', 'SMA', 'Latihan Materi', NULL, NULL, NULL);
